version: 2
jobs:
  lighthouse:
    docker:
      - image: circleci/node:16-browsers

    working_directory: ~/repo

    steps:
      - run:
          name: Debug
          command: npm -v;yarn -v;node -v

      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}

      - run: yarn --pure-lockfile

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run: yarn run start

workflows:
  version: 2
  manual_workflow:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only:
                - master
      - lighthouse:
          requires:
            - hold
  scheduled_workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *" # UTC, every day
          filters:
            branches:
              only:
                - master
    jobs:
      - lighthouse
